[package]
name = "cark-server"
version = "0.1.0"
edition = "2021"

[dependencies]
cark-common = { path = "../cark-common" }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
